package translator

// translateProviders handles rule-providers.
// mihomo rule-providers use Clash-specific formats (classical/domain/ipcidr) that are
// incompatible with sing-box rule-set format (binary .srs or JSON source).
// All rule-providers are skipped; only GEOIP/GEOSITE rule-sets (generated by the
// translator from rule.go) are included in the output.
func translateProviders(cfg *RawConfig, t *translation) {
	if cfg.RuleProvider == nil {
		return
	}

	for name := range cfg.RuleProvider {
		t.warn("rule-provider \"" + name + "\" skipped: mihomo rule-provider formats are incompatible with sing-box")
	}
}
